### ISSUE TITLE
Elastic index configuration using type static with fluent-plugin-viaq failing with ERROR

### ISSUE THREAD

**Issue by abu-2020-ghub** [openshift/cluster-logging-operator#644] opened 2020-08-04 14:19 UTC
Trying the below configuration with fluent-plugin-viaq in OCP 4.4 (openshift-logging operator), but it fails with ERROR
```
<elasticsearch_index_name>
     enabled "true"
     tag "myapp*"
     name_type static
     static_index_name myapp
</elasticsearch_index_name>
```

```
[]# oc logs -c fluentd fluentd-ccb4l
2020-08-03 03:37:22 +0000 [error]: config error file="/etc/fluent/fluent.conf" error_class=Fluent::ConfigError error="valid options are operations_full,project_full,operations_prefix,project_prefix,audit_full,audit_prefix but got static"
```

Any support would help !!

**Comment by jcantrill** [comment] 2020-08-04 15:15
Closed duplicate of https://github.com/openshift/origin-aggregated-logging/issues/1957

**Closed by jcantrill** 2020-08-04 15:15 UTC
